/******************************************************************************
*  ____                  _
* |  _ \  ___  _ __ ___ (_)_ __   ___
* | | | |/ _ \| '_ ` _ \| | '_ \ / _ \
* | |_| | (_) | | | | | | | | | | (_) |
* |____/ \___/|_| |_| |_|_|_| |_|\___/
* ____________________________________________________________________________
* Sponsor              : Domino
* Compund              : -
* Study                : -
* Analysis             : -
* Program              : domino.sas
* ____________________________________________________________________________
* DESCRIPTION 
*
* This is the standard Domino SAS setup file and contains definitions that
* are used across the reporting effort. 
*
* DO NOT EDIT THIS FILE
*
*****************************************************************************/
 
%macro __setup();

* globals read in from env vars; 
%global __WORKING_DIR  ; * path to root of working directory ;
%let __WORKING_DIR  = %sysget(DOMINO_WORKING_DIR);
 
* other globals exported by setup;
%global __prog_name;     * filename (without extension) of program;
%global __results_path;  * path to output file (e.g. for TFL write);
%global __full_path;     * full path and filename of program;
%global __runmode;       * INTERACTIVE or BATCH (or UNKNOWN);

 
* ==================================================================;
* work out if the project is git or domino based
* ==================================================================;
* !!ALERT!! DOMINO_IS_GIT_BASED is an undocumented environment variable;
%let __is_git_project = %sysget(DOMINO_IS_GIT_BASED);
%if %upcase(&__is_git_project) eq %str(TRUE) %then %do;
  %let __results_path=/mnt/artifacts/results;
%end; %else %do;
  %let __results_path=&__WORKING_DIR./results;
%end;
 
* ==================================================================;
* Determine if we are running Interactive or Batch ;
* ==================================================================;
 
* default position is that we dont know how program is running;
%let __runmode=UNKNOWN;
 
%* ------------------------------------------------------------------;
%* Are we running in INTERACTIVE mode? ;
%* Check for macro var _SASPROGRAMFILE. only present in SAS Studio ;
%* ------------------------------------------------------------------;
   %if %symexist(_SASPROGRAMFILE) %then %do;
      %let __full_path = %str(&_SASPROGRAMFILE.);
      %let __runmode=INTERACTIVE;
      %put %str(TR)ACE: (domino.sas) Running in SAS Studio.;
   %end;
 
%* ------------------------------------------------------------------;
%* Are we running in BATCH mode? ;
%* Check for Operating System parameter SYSIN. This parameter indicates batch execution ;
%* ------------------------------------------------------------------;
   %else %if %quote(%sysfunc(getoption(sysin))) ne %str() %then %do;
      %let __full_path = %quote(%sysfunc(getoption(sysin)));
      %let __runmode=BATCH;
      %put %str(TR)ACE: (domino.sas) Running in BATCH SAS.;
   %end;
 
%* Runtime check that we can identify runtime mode;
%if &__full_path eq %str() %then %put %str(WAR)NING: Cannot determine program name;
 
* ------------------------------------------------------------------;
* get program name, path and extension ;
* ------------------------------------------------------------------;
%local filename;
%* scan from right to left for first backslash. ;
%* everything to the right of that slash is filename with extension. ;
%let filename = %scan(&__full_path, -1, /);
 
%* isolate filename as everything up to but not including the period. ;
%let __prog_name = %scan(&filename, 1, .);
 
* ==================================================================;
* Redirect log files (BATCH MODE ONLY);
* ==================================================================;
%if &__runmode eq %str(BATCH) %then %do;
  * Redirect SAS LOG files when in batch mode;
  PROC PRINTTO LOG="&__results_path./&__prog_name..log" NEW;
%end;
 
%mend __setup;
* invoke the setup macro - so user program only needs to include this file;
%__setup;
 
* ==================================================================;
* write to log for traceability ;
* this is done outside the setup macro to ensure global vars are defined;
* ==================================================================;
%put TRACE: (domino.sas) [__WORKING_DIR = &__WORKING_DIR.] ;
%put TRACE: (domino.sas) [__prog_name = &__prog_name.];
%put TRACE: (domino.sas) [__results_path = &__results_path.];
%put TRACE: (domino.sas) [__runmode = &__runmode.];
 
* List all the libraries that are currently defined;
libname _all_ list;
 
*EOF;